# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAXXtreme Designs
email: maxxtremedesigns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MAXXtreme Designs is a web design, development, and deployment agency.
  Focused on pixel-perfect, scalable, and maintainable sites, MAXXtreme creates perfect static sites for companies & individuals.
baseurl: "/landing.html" # the subpath of your site, e.g. /blog
url: "http://www.maxxtremedesigns.com" # the base hostname & protocol for your site
twitter_username: MAXXtreme007
github_username:  MAXXtreme007

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
